# Generated by Django 4.0.3 on 2022-04-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Текст')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательский пост',
                'verbose_name_plural': 'Пользовательские посты',
            },
        ),
    ]
