# Generated by Django 4.0.3 on 2022-04-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_alter_user_options_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
