# Generated by Django 4.0.3 on 2022-04-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_remove_follow_follows_remove_follow_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='friends.user', verbose_name='Пользователь'),
        ),
    ]
